### ISSUE TITLE
Build versions on tag.

### ISSUE THREAD

**Issue by moxventura** [moxventura/daily-price-scraper-extension#7]
Let's do a zip for now
.github/workflows/package.yml
name: Package Chrome Extension

```
on:
  push:
    tags:
      - 'v*'  # This will trigger the workflow for tags that start with 'v'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install zip
        run: sudo apt-get install zip

      - name: Get version from tag
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Package versioned extension
        run: |
          zip -r "extension-${{ env.VERSION }}.zip" . -x "*.git*"
          
      - name: Upload ZIP artifacts
        uses: actions/upload-artifact@v2
        with:
          name: chrome-extension-${{ env.VERSION }}
          path: "extension-${{ env.VERSION }}.zip"
```
